library(tufte)
library(tidyverse)
library(ggplot2)
library(tint)
library(lubridate)
library(stringr)
library(tm)
load('tables.RData')

titleCorpus <- VCorpus(VectorSource(Papers$title))
titleCorpusClean <- tm_map(titleCorpus, content_transformer(tolower))
titleCorpusClean <- tm_map(titleCorpusClean, removeNumbers)
